web:
  build: .
  command: gin run go run server.go
  ports:
    - "3000:3000"
  volumes:
    - .:/go/src/github.com/asm-products/firesize
  links:
    - db
  environment:
    - DATABASE_URL=postgres://postgres@db/postgres?sslmode=disable

db:
  image: kiasaki/alpine-postgres:latest
  ports:
    - "5432"

webpack:
  build: scripts/webpack-docker
  volumes:
    - .:/app
